### ISSUE TITLE
4 person family groups not supported from Apple Color Emoji.ttf

### ISSUE THREAD

**Issue by joshbalfour** [devongovett/fontkit#26] opened 2016-02-19 23:14 UTC
```
let font = fontkit.openSync("/System/Library/Fonts/Apple Color Emoji.ttf");
let emojis = [ '👨‍👩‍👧‍👦','👨‍👩‍👦‍👦','👨‍👩‍👧‍👧', '👩‍👩‍👧‍👦','👩‍👩‍👦‍👦', '👩‍👩‍👧‍👧','👨‍👨‍👧‍👦', '👨‍👨‍👦‍👦','👨‍👨‍👧‍👧' ];

emojis.forEach(function(emoji){
	let layout;

	try {
		layout = font.layout(emoji);
	} catch (e) {
		console.error(`Error converting ${emoji} to image:`, e, e.stack);
	}
});
````

For each emoji produces

```
[TypeError: Cannot read property 'codePoints' of undefined] TypeError: Cannot read property 'codePoints' of undefined
    at AATMorxProcessor.processLigature (/Users/joshuabalfour/Projects/emoji-dating/misc/emojiXtract/node_modules/fontkit/src/aat/AATMorxProcessor.js:254:75)
    at /Users/joshuabalfour/Projects/emoji-dating/misc/emojiXtract/node_modules/fontkit/src/aat/AATMorxProcessor.js:4:59
    at AATStateMachine.process (/Users/joshuabalfour/Projects/emoji-dating/misc/emojiXtract/node_modules/fontkit/src/aat/AATStateMachine.js:55:11)
    at AATMorxProcessor.processSubtable (/Users/joshuabalfour/Projects/emoji-dating/misc/emojiXtract/node_modules/fontkit/src/aat/AATMorxProcessor.js:124:27)
    at AATMorxProcessor.process (/Users/joshuabalfour/Projects/emoji-dating/misc/emojiXtract/node_modules/fontkit/src/aat/AATMorxProcessor.js:81:18)
    at LayoutEngine.substitute (/Users/joshuabalfour/Projects/emoji-dating/misc/emojiXtract/node_modules/fontkit/src/layout/LayoutEngine.js:99:28)
    at LayoutEngine.layout (/Users/joshuabalfour/Projects/emoji-dating/misc/emojiXtract/node_modules/fontkit/src/layout/LayoutEngine.js:84:21)
    at TTFFont.layout (/Users/joshuabalfour/Projects/emoji-dating/misc/emojiXtract/node_modules/fontkit/src/TTFFont.js:218:33)
    at /Users/joshuabalfour/Projects/emoji-dating/misc/emojiXtract/Apple Color Emoji.js:35:17
    at Array.forEach (native)
```

**Comment by Pomax** [comment] 2016-02-20 00:19
is this a real ttf, or an aat font that Apple has decided to give the .ttf extension?

**Comment by devongovett** [comment] 2016-02-20 19:17
Duplicate of #20, which was fixed a while ago. Sorry for not doing an npm release in a bit. Just did v1.2.0.

**Closed by devongovett** 2016-02-20 19:17 UTC

**Comment by joshbalfour** [comment] 2016-02-20 23:12
@devongott Thank you!!
