### ISSUE TITLE
Get a whole word as *.svg

### ISSUE THREAD

**Issue by pwichmann** [devongovett/fontkit#79] opened 2017-04-05 18:27 UTC
Is it possible to get a whole word as an *.svg and not only a single letter?

So if we take the example...

> var fontkit = require('fontkit');
> 
> var font = fontkit.openSync('font.ttf');
> 
> var run = font.layout('hello!');
> 
> // get an SVG path for a glyph
> var svg = run.glyphs[0].path.toSVG();

...would it be possible to get the whole word 'hello!' as one SVG?

I don't want to iterate over the glyphs array since it would become impossible for me to correctly align each individual letter of a word once they have been separated.

Do I make sense at all?
Many thanks for any help!

**Comment by Pomax** [comment] 2017-04-05 18:51
This sounds like a duplicate of https://github.com/devongovett/fontkit/issues/24

**Comment by pwichmann** [comment] 2017-04-05 18:59
Thank you, Pomax.

I am not sure I could see any solution offered in #24.

I might be stupid again (as in my last issue), but:
Would exporting each glyph into individual paths not result in losing the property of having all letters correctly scaled and positioned/aligned? I would not know how to align letters the way the font designer intended to align the letters.

**Comment by Pomax** [comment] 2017-04-05 19:34
There is no solution, but all solutions start with an issue filed to ask for that solution to be implemented =)

**Comment by pwichmann** [comment] 2017-04-05 19:44
I commented on #24 and expressed my support as well as explained my needs.

**Closed** 2017-04-23 17:55 UTC
