### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by defue** [devongovett/fontkit#32] opened 2016-03-21 08:56 UTC
Code:

```
var fontkit = require('fontkit');
var font = fontkit.openSync('Confetti Regular.ttf');
var run = font.layout('hello world!');
```

Output:

```
/home/defue/node_modules/brotli/build/decode.js:1
orts, require, module, __filename, __dirname) { function e(a){throw a;}var j=v
                                                                    ^
TypeError: Cannot read property 'length' of null
    at GSUBProcessor.OTProcessor.findScript (/home/defue/node_modules/fontkit/src/opentype/OTProcessor.js:29:28)
    at GSUBProcessor.OTProcessor.selectScript (/home/defue/node_modules/fontkit/src/opentype/OTProcessor.js:56:24)
    at GSUBProcessor.OTProcessor (/home/defue/node_modules/fontkit/src/opentype/OTProcessor.js:20:12)
    at new GSUBProcessor (/home/defue/node_modules/fontkit/src/opentype/GSUBProcessor.js:16:50)
    at new OTLayoutEngine (/home/defue/node_modules/fontkit/src/opentype/OTLayoutEngine.js:20:30)
    at new LayoutEngine (/home/defue/node_modules/fontkit/src/layout/LayoutEngine.js:25:129)
    at TTFFont.layout (/home/defue/node_modules/fontkit/src/TTFFont.js:216:30)
    at Object.<anonymous> (/home/defue/Tagul/svn/Frontend/canvasForm/components/fontkit/test.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

Nodejs v0.10.25
Fontkit v
[Confetti Regular.ttf.zip](https://github.com/devongovett/fontkit/files/181854/Confetti.Regular.ttf.zip)
1.2.1

**Comment by devongovett** [comment] 2016-03-21 16:21
Fixed by the above commit. Was caused by a GSUB table with a null script list.

**Closed** 2016-03-21 16:21 UTC
